version: '3'
services:
 qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ = Asia/Taipei
    volumes:
      - /home/ppksgopin/Downloads/bt/config:/config 
      - /home/ppksgopin/Downloads/bt/downloads:/downloads
    ports:
      - 8080:8080 
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped